### ISSUE TITLE
Combine SQL statements in MapChallenge 28

### ISSUE THREAD

**Issue by SK53** [VictimOfMaths/30DayMapChallenge2022#1]
Sorry for not responding on Twitter, but for various reasons have been silent there for a couple of years, and also apologies for nit-picking on a one-off map challenge.

I was intrigued by this particular map because I built [some cartograms](https://www.flickr.com/search/?sort=date-taken-desc&safe_search=1&tags=cartogram&user_id=43047002%40N06&view_all=1) of pubs (& a range of other retail elements) from OSM data back in 2015, and because I've never used R to build maps. 

Looking at the code it struck me that the 4 initial SQL statements could be combined : 

`SELECT * FROM \"amenity_EPSG4326_point\" WHERE amenity IN ('pub','bar','nightclub','biergarten')")`

This ought to have better performance. No guarantees though.

One other point is that I found the generalisation of Natural Earth boundaries, either placed a few POIs in the wrong country or lost them in some coastal cities (_e.g.,_ Buenos Aires) with a straight join using `ST_Within`. After trying out various things, I ended up using the more precise OSM boundaries which take a long time to build. A rather long write-up [here](http://sk53-osm.blogspot.com/2015/05/retail-outlets-on-openstreetmap.html).

Jerry Clough aka SK53

**Comment by VictimOfMaths** [comment]
Thanks - that is literally the first SQL statement I've written in my life, so I'm not surprised it's inefficient, although I actually made a deliberate choice to extract them as separate files in case in future I want to mess about with only some subset of them.

I'm not in the least surprised that the assignment to countries falls over sometimes. it's certainly something I'd like to fix before using this approach for anything more formal, but I decided this was acceptable for a quick map challenge map (in the same way I lazily used the population estimates in the natural earth data, and didn't properly fix the disputed territories). It's useful to have an approach to do it better set out nicely, thanks.
